version: "3"
services:
  yarmak:
    image: python:3.8-alpine3.16
#    container_name: yarmak
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    volumes:
      - /home/tele_tok/:/usr/src/app/token/
    environment:
      - TZ=Europe/Moscow
    build:
      context: ./find_doctor
      dockerfile: Dockerfile_compose
    command: python3 find_doctor.py --name Ярмак
  nikolaeva:
    image: python:3.8-alpine3.16
#    container_name: battalova
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    volumes:
      - /home/tele_tok/:/usr/src/app/token/
    environment:
      - TZ=Europe/Moscow
    build:
      context: ./find_doctor
      dockerfile: Dockerfile_compose
    command: python3 find_doctor.py --name Николаева
  orlova:
    image: python:3.8-alpine3.16
    #    container_name: orlova
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    volumes:
      - /home/tele_tok/:/usr/src/app/token/
    environment:
      - TZ=Europe/Moscow
    build:
      context:  ./find_doctor
      dockerfile: Dockerfile_compose
    command: python3 find_doctor.py --name Орлова
  stomatologi:
    image: python:3.8-alpine3.16
    #    container_name: orlova
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    volumes:
      - /home/tele_tok/:/usr/src/app/token/
    environment:
      - TZ=Europe/Moscow
    build:
      context: ./find_doctor
      dockerfile: Dockerfile_compose
    command: python3 find_doctor.py --name Стоматология
  ortoped:
    image: python:3.8-alpine3.16
    #    container_name: orlova
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    volumes:
      - /home/tele_tok/:/usr/src/app/token/
    environment:
      - TZ=Europe/Moscow
    build:
      context: ./find_doctor
      dockerfile: Dockerfile_compose
    command: python3 find_doctor.py --name Батталова