version: "3"
services:
  nikolaeva:
    image: python:3.8-alpine3.16
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    volumes:
      - /home/tele_tok/:/usr/src/app/token/
    environment:
      - TZ=Europe/Moscow
    build:
      context: ./find_doctor
      dockerfile: Dockerfile_compose
    command: python3 find_doctor.py --name Николаева --config_file 11347.json
  yarmak:
    image: python:3.8-alpine3.16
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    volumes:
      - /home/tele_tok/:/usr/src/app/token/
    environment:
      - TZ=Europe/Moscow
    build:
      context: ./find_doctor
      dockerfile: Dockerfile_compose
    command: python3 find_doctor.py --name Ярмак --config_file 11347.json
  gromov:
    image: python:3.8-alpine3.16
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    volumes:
      - /home/tele_tok/:/usr/src/app/token/
    environment:
      - TZ=Europe/Moscow
    build:
      context: ./find_doctor
      dockerfile: Dockerfile_compose
    command: python3 find_doctor.py --name Громов --config_file 10392.json
  demyanenko:
    image: python:3.8-alpine3.16
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    volumes:
      - /home/tele_tok/:/usr/src/app/token/
    environment:
      - TZ=Europe/Moscow
    build:
      context: ./find_doctor
      dockerfile: Dockerfile_compose
    command: python3 find_doctor.py --name Демяненко --config_file 11652.json
  subbot:
    image: python:3.8-alpine3.16
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    volumes:
      - /home/tele_tok/:/usr/src/app/token/
    environment:
      - TZ=Europe/Moscow
    build:
      context: ./find_doctor
      dockerfile: Dockerfile_compose
    command: python3 find_doctor.py --name Суббот --config_file 11651.json
